# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "277b97d87c7ece01e34a3b2e0fb84d8b"
name = "Request A Quote"
application_url = "https://namely-finer-seasnail.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,write_draft_orders,read_themes,write_themes,write_orders,read_shipping,read_discounts,read_fulfillments"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://namely-finer-seasnail.ngrok-free.app/authenticate" ]

[app_preferences]
url = "https://namely-finer-seasnail.ngrok-free.app/authenticate"
